# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Lumberjack
                                 A QGIS plugin
 This plugin calculates features of images, classifies and removes trees out of elevation maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-07-01
        copyright            : (C) 2019 by UNICEN
        email                : bruscantinic@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Lumberjack class from file Lumberjack.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Lumberjack import Lumberjack
    return Lumberjack(iface)
