# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LumberjackDialog
                                 A QGIS plugin
 This plugin is meant to removes trees out of elevation maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-07-01
        git sha              : $Format:%H$
        copyright            : (C) 2019 by UNICEN
        email                : bruscantinic@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5 import uic, QtCore
from PyQt5 import QtWidgets, QtGui

# This loads your .ui file so that PyQt can populate
# your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Lumberjack_dialog_base.ui'))


class LumberjackDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(LumberjackDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        # self.pushButton_feature_importances.setIcon(QtGui.QIcon(':/plugins/Lumberjack/barchart.png'))
        # self.pushButton_feature_importances.setIconSize(QtCore.QSize(40,40))
